version: '3'

tasks:
  help:
    desc: 利用可能なタスク一覧を表示する
    cmds:
      - task --list

  clean-tf:
    desc: Terraformの状態ファイルを全て削除する
    cmds:
      - rm -rf .terraform
      - rm .terraform.lock.hcl
      - rm terraform.tfstate
      - rm terraform.tfstate.backup
    silent: true

  init-tf:
    desc: Terraformを初期化する
    cmds:
      - terraform init
    silent: true

  apply-tf:
    desc: Terraformでリソースを作成する
    cmds:
      - terraform apply -var-file terraform.tfvars -auto-approve
    silent: true

  destroy-tf:
    desc: Terraformでリソースを削除する
    cmds:
      - terraform destroy -var-file terraform.tfvars -auto-approve
    silent: true
